#
# https://swagger.io/docs/specification/basic-structure/
#
#
openapi: 3.0.0
info:
  title: obotix-api
  description: Developer API documentation for the [obotix-api](https://github.com/webjestic/obotix-api) backend server.
  version: 0.1.0
